version: '3.9'
services:
  db:
    image: postgres:14.9-alpine
    container_name: postgresql
    ports:
      - '5432:5432'
    expose:
      - '5432'
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - ./pg-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: application
    ports:
      - 3000:8080
    environment:
      - DB_HOST=db
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_USER=$POSTGRES_USER
      - DB_NAME=$POSTGRES_DB
    restart: always
    depends_on:
      db:
        condition: service_healthy
